Repository fac-17/Generation-Change, pull requests merged in 2019-10, with the labels that each got.

#12 added normalize sass and variables files
  src/App.js
  src/App.sass
  src/components/LandingPage/LandingPage.js
  src/index.css
  src/index.js
  src/styles/App.sass
  src/styles/Normalize.sass
  src/styles/Variables.sass
  src/tests/App.test.js
Labels: blocking, design, important 1, setup

#15 Style guide
  package-lock.json
  package.json
  src/App.js
  src/index.js
  src/styles/App.sass
  src/styles/StyleGuide.js
  src/styles/Variables.sass
Labels: design, setup

#28 Feature/lambdaandapi
  .gitignore
  _redirects
  netlify.toml
  package-lock.json
  package.json
  src/App.js
  src/utils/getData.js
Labels: database, devops

#29 move functions folder outside of git ignore
  functions/getdata/getdata.js
  netlify.toml
Labels: blocking, bug, database, devops

#34 update toml filepath
  functions/getdata/getdata.js
  netlify.toml
Labels: bug

#38 Feature/search bar component
  src/App.js
  src/components/Universal/Searchbar.js
  src/utils/convertPostcode.js
Labels: feature

#45 fix failing test
  src/tests/Utils.test.js
  src/utils/convertPostcode.js
Labels: bug, testing

#47 Feature/testing
  src/components/DetailsPage/DetailsPage.js
  src/components/LandingPage/LandingPage.js
  src/components/LandingPage/Navbar.js
  src/components/ResultsPage/Navbar.js
  src/components/ResultsPage/ResultsPage.js
  src/components/StoriesPage/Navbar.js
  src/components/StoriesPage/StoriesPage.js
  src/components/Universal/Navbar.js
  src/components/Universal/Searchbar.js
  src/tests/UniversalComponents.test.js
  src/tests/Utils.test.js
Labels: testing

#52 Feature/results
  package-lock.json
  package.json
  src/App.js
  src/components/ResultsPage/ProjectCards.js
  src/components/ResultsPage/ResultsPage.js
  src/components/ResultsPage/data.js
Labels: feature

#64 Leaflet
  package-lock.json
  package.json
  src/components/ResultsPage/LeafletMap.js
  src/components/ResultsPage/Map.js
  src/components/ResultsPage/ResultsPage.js
  src/styles/App.sass
Labels: feature

#74 Filter by distance
  src/components/ResultsPage/index.js
Labels: important 1

#78 Project page
  src/App.js
  src/components/DetailsPage/ProjectDetails.js
  src/components/DetailsPage/index.js
  src/components/ResultsPage/ProjectCards.js
  src/components/ResultsPage/index.js
Labels: database

#85 Maps
  package-lock.json
  package.json
  public/index.html
  src/App.js
  src/components/ResultsPage/LeafletMap.js
  src/styles/App.sass
  src/utils/postData.js
Labels: important 1, map

#87 Maps
  src/App.js
  src/components/ResultsPage/LeafletMap.js
  src/components/ResultsPage/index.js
Labels: important 1, map

#90 Test functions
  src/components/ResultsPage/index.js
  src/tests/Utils.test.js
  src/utils/dataManipulation.js
Labels: testing

#91 remove warnings
  src/App.js
  src/components/DetailsPage/ImageContainer.js
  src/components/DetailsPage/ProjectSummary.js
  src/components/ResultsPage/LeafletMap.js
  src/components/ResultsPage/ProjectCards.js
  src/components/ResultsPage/index.js
  src/components/Universal/Svg.js
Labels: bug

#95 Feature/link markers to results
  src/App.js
  src/components/ResultsPage/LeafletMap.js
  src/components/ResultsPage/index.js
  src/tests/showResultsAsMarkers.test.js
  src/utils/showResultsAsMarkers.js
Labels: important 1

#96 Style map
  cypress/integration/examples/actions.spec.js
  cypress/integration/examples/aliasing.spec.js
  cypress/integration/examples/assertions.spec.js
  cypress/integration/examples/connectors.spec.js
  cypress/integration/examples/cookies.spec.js
  cypress/integration/examples/cypress_api.spec.js
  cypress/integration/examples/files.spec.js
  cypress/integration/examples/local_storage.spec.js
  cypress/integration/examples/location.spec.js
  cypress/integration/examples/misc.spec.js
  cypress/integration/examples/navigation.spec.js
  cypress/integration/examples/network_requests.spec.js
  cypress/integration/examples/querying.spec.js
  cypress/integration/examples/sample_spec.js
  cypress/integration/examples/spies_stubs_clocks.spec.js
  cypress/integration/examples/traversal.spec.js
  cypress/integration/examples/utilities.spec.js
  cypress/integration/examples/viewport.spec.js
  cypress/integration/examples/waiting.spec.js
  cypress/integration/examples/window.spec.js
  cypress/integration/home_page_spec.js
  cypress/plugins/index.js
  src/App.js
  src/components/LandingPage/Title.js
  src/components/LandingPage/index.js
  src/components/ResultsPage/LeafletMap.js
  src/components/ResultsPage/ProjectCards.js
  src/components/ResultsPage/index.js
  src/components/Universal/Searchbar.js
  src/styles/App.sass
  src/styles/Variables.sass
  src/tests/UniversalComponents.test.js
  src/tests/Utils.test.js
  src/tests/showResultsAsMarkers.test.js
  src/utils/dataManipulation.js
  src/utils/showResultsAsMarkers.js
Labels: blocking, bug, design, feature, map, testing

#98 fix broken favicon link
  public/index.html
Labels: bug

#99 Center map
  src/App.js
  src/components/ResultsPage/LeafletMap.js
Labels: bug, design, map

#97 amend results title
  src/components/ResultsPage/index.js
Labels: bug

#100 fix map to right
  src/styles/App.sass
Labels: bug, map

#101 Story pages
  src/App.js
  src/components/LandingPage/Stories.js
  src/components/LandingPage/index.js
  src/styles/App.sass
Labels: design

#107 Style landing stories
  public/statics/story2.jpg
  public/statics/story3.jpg
  src/components/LandingPage/Stories.js
  src/styles/App.sass
Labels: bug

#111 Feature/styling tine
  src/App.js
  src/components/DetailsPage/ProjectSummary.js
  src/components/StoriesPage/index.js
Labels: feature

#114 Feauture/center map
  src/components/ResultsPage/LeafletMap.js
  src/components/ResultsPage/index.js
Labels: feature

#115 fix broken link on story page title
  src/components/StoriesPage/index.js
  src/styles/App.sass
Labels: bug

#116 Feature/save data reload
  package-lock.json
  package.json
  src/components/DetailsPage/index.js
  src/components/ResultsPage/LeafletMap.js
  src/components/ResultsPage/index.js
  src/components/Universal/Searchbar.js
Labels: bug

#126 Fix/bugs
  .netlify/functions/getdata/getdata.js
  src/App.js
  src/components/DetailsPage/index.js
  src/components/LandingPage/Stories.js
  src/components/ResultsPage/LeafletMap.js
  src/components/ResultsPage/index.js
  src/components/StoriesPage/index.js
  src/components/Universal/Searchbar.js
  src/utils/showResultsAsMarkers.js
Labels: bug

#129 404
  src/App.js
  src/components/ResultsPage/ProjectCards.js
  src/components/Universal/404.js
  src/components/Universal/Loading.js
  src/styles/App.sass
Labels: important 1

#128 Feature/clean up
  src/components/DetailsPage/ProjectSummary.js
  src/components/LandingPage/Stories.js
  src/components/ResultsPage/ProjectCards.js
  src/components/StoriesPage/index.js
  src/styles/App.sass
Labels: enhancement

#130 Feature/marker
  fac/.formatter.exs
  fac/.gitignore
  fac/README.md
  fac/lib/fac.ex
  fac/mix.exs
  fac/test/fac_test.exs
  fac/test/test_helper.exs
  src/components/ResultsPage/LeafletMap.js
  src/styles/App.sass
Labels: enhancement
